language: node_js
node_js:
  - '8'
  - '10'

cache: npm

deploy:
  provider: npm
  email: akhe@grodansparadis.com
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
    - akhe@grodansparadis.com
    on_success: change
    on_failure: always